enableGitInfo = false
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
theme = "resume"
title = "Hugo Cortes"

[params]
    address = "Los Angeles, CA"
    contactNote = "Software Engineer"
    email = "contact@hugocortes.dev"
    favicon = "favicon.ico"
    firstName = "Hugo"
    lastName = "Cortes"
    phone = ""
    profileImage = "https://res.cloudinary.com/hugocortes/image/upload/v1589467648/hugo.jpg"
    showBlog = true
    showEducation = true
    showExperience = true
    showOpenSource = true
    showProjects = false
    showPublications = false
    showQr = true
    showSkills = true

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/cortes-hugo/"

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/hugocortes"

[outputs]
  home = ["HTML", "JSON"]

[taxonomies]
    tag = "tags"
